# Generated by Django 5.1.4 on 2024-12-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebookapp', '0002_alter_phonebook_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='phonebook',
            new_name='phonebook1',
        ),
    ]
